### PR TITLE
refactor redirect uri, allow redirect from register

### PR DESCRIPTION
**Pull request by jharrilim**
Allow new users to be redirected back to tg/slack after they have registered.

### CODE REVIEW

**Comment by jharrilim** [comment]
[Redirect New Users back to Chat Application](https://trello.com/c/o9nIIF5m/111-redirect-new-users-back-to-chat-application)

**Review by poulad — CHANGES_REQUESTED** [review]
Why redirect to an external URI after registration?

I'm not sure if we currently have a use case for it. AFAIK, Chat bots are supposed to be used by an existing Zevere user who has registered and knows the app.

**Comment by jharrilim** [comment]
Why would we even make that assumption? They can install the Zevere App/Bot before they even touch Zevere. The App directory on Slack could be an entrypoint for people getting into Zevere. We have absolutely no reason to punish people for coming from Slack when it is easy to make it accessible.

**Comment by poulad** [comment]
Sure. It makes sense.

**Comment by poulad** [comment]
There is no requirement for redirection to a URI with the `tg` scheme. I remove that.

**Pull request merged**
